// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MythicalCreatures.Server.Data;

#nullable disable

namespace MythicalCreatures.Server.Migrations
{
    [DbContext(typeof(MythicalCreaturesDbContext))]
    [Migration("20260515011721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MythicalCreatures.Server.Models.Ability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatureId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.ToTable("Abilities");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Creature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatureTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateFirstSighted")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PowerLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CreatureTypeId");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.CreatureType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CreatureTypes");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.CreatureXRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatureId")
                        .HasColumnType("int");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatureId");

                    b.HasIndex("RegionId");

                    b.ToTable("CreatureXRegion");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Climate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Ability", b =>
                {
                    b.HasOne("MythicalCreatures.Server.Models.Creature", "Creature")
                        .WithMany("Abilities")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Creature", b =>
                {
                    b.HasOne("MythicalCreatures.Server.Models.CreatureType", "CreatureType")
                        .WithMany("AllCreatures")
                        .HasForeignKey("CreatureTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatureType");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.CreatureXRegion", b =>
                {
                    b.HasOne("MythicalCreatures.Server.Models.Creature", "Creature")
                        .WithMany("FoundInRegions")
                        .HasForeignKey("CreatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MythicalCreatures.Server.Models.Region", "Region")
                        .WithMany("RegionWithCreature")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creature");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Creature", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("FoundInRegions");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.CreatureType", b =>
                {
                    b.Navigation("AllCreatures");
                });

            modelBuilder.Entity("MythicalCreatures.Server.Models.Region", b =>
                {
                    b.Navigation("RegionWithCreature");
                });
#pragma warning restore 612, 618
        }
    }
}
